version: "3"
services:
  nats1:
    image: nats:latest
    hostname: nats1
    command: "-c /swarm.conf"
    volumes:
      - "~/nats/nats-tls-cluster/swarm.conf:/swarm.conf"
    ports:
      - "4222:4221"
      - "8222:8221"
  nats2:
    image: nats:latest
    hostname: nats2
    command: "-c /tls-swarm.conf"
    volumes:
      - "~/nats/nats-tls-cluster/swarm.conf:/swarm.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
  nats3:
    image: nats:latest
    hostname: nats3
    command: "-c /tls-swarm.conf"
    volumes:
      - "~/nats/nats-tls-cluster/swarm.conf:/swarm.conf"
    ports:
      - "4222:4223"
      - "8222:8223"
networks:
  default:
    external:
      name: nats-cluster