version: "3"
services:
  nats:
    image: nats:latest
    hostname: nats-main
    command: "-c /tls.conf"
    volumes:
      - "./tls.conf:/tls.conf"
      - "./certs/server.pem:/certs/server.pem"
      - "./certs/server-key.pem:/certs/server-key.pem"
      - "./certs/ca.pem:/certs/ca.pem"
      - "./certs/route.pem:/certs/route.pem"
      - "./certs/route-key.pem:/certs/route-key.pem"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
