version: "3"
services:
  nats1:
    image: nats:latest
    hostname: nats1
    command: "-c /swarm-tls.conf"
    volumes:
      - "~/nats/nats-tls-cluster/swarm-tls.conf:/swarm-tls.conf"
      - "~/nats/nats-tls-cluster/certs/server.pem:/certs/server.pem"
      - "~/nats/nats-tls-cluster/certs/server-key.pem:/certs/server-key.pem"
      - "~/nats/nats-tls-cluster/certs/ca.pem:/certs/ca.pem"
      - "~/nats/nats-tls-cluster/certs/route-docker-swarm.pem:/certs/route-docker-swarm.pem"
      - "~/nats/nats-tls-cluster/certs/route-docker-swarm-key.pem:/certs/route-docker-swarm-key.pem"
    ports:
      - "4221:4222"
      - "8221:8222"
    networks:
      default:
        aliases:
          - nats1.my-nats-cluster
  nats2:
    image: nats:latest
    hostname: nats2
    command: "-c /swarm-tls.conf"
    volumes:
      - "~/nats/nats-tls-cluster/swarm-tls.conf:/swarm-tls.conf"
      - "~/nats/nats-tls-cluster/certs/server.pem:/certs/server.pem"
      - "~/nats/nats-tls-cluster/certs/server-key.pem:/certs/server-key.pem"
      - "~/nats/nats-tls-cluster/certs/ca.pem:/certs/ca.pem"
      - "~/nats/nats-tls-cluster/certs/route-docker-swarm.pem:/certs/route-docker-swarm.pem"
      - "~/nats/nats-tls-cluster/certs/route-docker-swarm-key.pem:/certs/route-docker-swarm-key.pem"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      default:
        aliases:
          - nats2.my-nats-cluster
  nats3:
    image: nats:latest
    hostname: nats3
    command: "-c /swarm-tls.conf"
    volumes:
      - "~/nats/nats-tls-cluster/swarm-tls.conf:/swarm-tls.conf"
      - "~/nats/nats-tls-cluster/certs/server.pem:/certs/server.pem"
      - "~/nats/nats-tls-cluster/certs/server-key.pem:/certs/server-key.pem"
      - "~/nats/nats-tls-cluster/certs/ca.pem:/certs/ca.pem"
      - "~/nats/nats-tls-cluster/certs/route-docker-swarm.pem:/certs/route-docker-swarm.pem"
      - "~/nats/nats-tls-cluster/certs/route-docker-swarm-key.pem:/certs/route-docker-swarm-key.pem"
    ports:
      - "4223:4222"
      - "8223:8222"
    networks:
      default:
        aliases:
          - nats3.my-nats-cluster
networks:
  default:
    external:
      name: nats-cluster